### ISSUE TITLE
Page to Edge Extension not found

### ISSUE THREAD

**Issue by ruudschouten** [andrewbrey/netflix-tweaked#11]
I didn't fill in all details for a bug report, since I thought this isn't really a bug with this project, but I assume with Microsoft.

**Describe the bug**
Windows Store link Extension [page](https://www.microsoft.com/store/apps/9MZ4BW66H3ZG) leads to a page with the following on it:

> We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available.

**To Reproduce**
1. Click on the "Download from Windows Store" button.

**Comment by andrewbrey** [comment]
@ruudschouten The link for the Microsoft store was broken by Microsoft when they updated their extension branding guidelines. Since this extension uses "Netflix" in the title, they decided to reject the extension for their store listings, even though it had passed review previously. To make it even more frustrating, they clearly do not uniformly enforce this policy as there are tons of other extensions that seem to break the exact same guideline. For now, I have simply removed the reference to the Windows store page from the documentation, and my extension will no longer indicate support for Edge. Hopefully Microsoft gets their act together and fixes their extremely painful and inconsistent extension policies because they are only going to lose potential users of their browser from it. Sorry to disappoint about the lack of Edge support for now...here's hoping we can update it to include Edge again at some point 😑
