### ISSUE TITLE
More user friendly "My List" 

### ISSUE THREAD

**Issue by 204ndri** [andrewbrey/netflix-tweaked#17]
The "My List" feature from Netflix is great for keeping track of your series but not really user friendly considering that it frequently gets shuffled and has no way of telling at first glance what has been watched and what has not. 
Therefor it would be nice if series you finished watching are grey scaled. 

To distinguish those you have not yet watched and those with new episodes, you could keep the series with new episodes available gray scaled with a "New Episodes" banner (not gray scaled). Though it would have to be added separately because as far as I can tell the already existing banner is part of the cover. I suppose this could prove to be rather tricky and there are other ways to resolve this.

**Comment by andrewbrey** [comment]
@204ndri This is not really something that Netflix Tweaked is intended to address, though I agree it would be great if Netflix implemented things like this since it's what users want. NT is really only meant to address the two principle concerns of auto-play trailers and reording the lists to put your first, so I'm marking this issue as "won't fix" and closing it. Some day, when I have more bandwidth to work on some of the larger nice-to-haves, I can expand the scope of what NT is meant for, but for now I need to keep it focused or else I'll never be able to keep up with it :)
